/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomodulacionv1.pkg1;

import java.awt.BorderLayout;

/**
 *
 * @author ibrah
 */
public class pantallaInicial extends javax.swing.JFrame {
    
   
    /**
     * Creates new form pantallaInicial
     */
    public pantallaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelDatos = new javax.swing.JPanel();
        jText_VcPm = new javax.swing.JTextField();
        jText_VmPm = new javax.swing.JTextField();
        jText_FcPm = new javax.swing.JTextField();
        jText_FmPm = new javax.swing.JTextField();
        jText_K = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButtonMod = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jText_Tiempo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRB_PM = new javax.swing.JRadioButton();
        jRB_FM = new javax.swing.JRadioButton();
        jPanel_Sin_modular = new javax.swing.JPanel();
        jPanel_S_Moduladora = new javax.swing.JPanel();
        jPanelModulada = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jText_VcPm.setText("5");

        jText_VmPm.setText("2");

        jText_FcPm.setText("7");
        jText_FcPm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_FcPmActionPerformed(evt);
            }
        });

        jText_FmPm.setText("3");

        jText_K.setText("4");

        jLabel1.setText("Amplitud portadora(Vc)");

        jLabel2.setText("V");

        jLabel3.setText("Amplitud moduladora");

        jLabel4.setText("V");

        jLabel5.setText("Frecuencia portadora");

        jLabel6.setText("Frecuencia moduladora");

        jLabel7.setText("Hz");

        jLabel8.setText("Hz");

        jLabel9.setText("sensibilidad a la desvicion");

        jLabel10.setText("rad/v");

        jButtonMod.setText("Modular");
        jButtonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinusoidal", "Cosenoidal", "Diente e' cierra", "triangular" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinusoidal", "Cosenoidal", "Diente e' cierra", "triangular" }));

        jText_Tiempo.setText("2");

        jLabel11.setText("tiempo");

        buttonGroup1.add(jRB_PM);
        jRB_PM.setText("PM");

        buttonGroup1.add(jRB_FM);
        jRB_FM.setText("FM");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_VmPm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_FmPm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jRB_PM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRB_FM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_VcPm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jText_FcPm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jButtonMod, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_K, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jText_FcPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jText_K, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jText_VcPm, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRB_PM)
                        .addComponent(jRB_FM)))
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jText_Tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMod)
                            .addComponent(jComboBox2)
                            .addComponent(jComboBox1))
                        .addContainerGap())
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_VmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_FmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(33, 33, 33))))
        );

        getContentPane().add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 900, 90));

        jPanel_Sin_modular.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel_Sin_modularLayout = new javax.swing.GroupLayout(jPanel_Sin_modular);
        jPanel_Sin_modular.setLayout(jPanel_Sin_modularLayout);
        jPanel_Sin_modularLayout.setHorizontalGroup(
            jPanel_Sin_modularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel_Sin_modularLayout.setVerticalGroup(
            jPanel_Sin_modularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_Sin_modular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 900, -1));

        jPanel_S_Moduladora.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel_S_ModuladoraLayout = new javax.swing.GroupLayout(jPanel_S_Moduladora);
        jPanel_S_Moduladora.setLayout(jPanel_S_ModuladoraLayout);
        jPanel_S_ModuladoraLayout.setHorizontalGroup(
            jPanel_S_ModuladoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel_S_ModuladoraLayout.setVerticalGroup(
            jPanel_S_ModuladoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel_S_Moduladora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 900, -1));

        jPanelModulada.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanelModuladaLayout = new javax.swing.GroupLayout(jPanelModulada);
        jPanelModulada.setLayout(jPanelModuladaLayout);
        jPanelModuladaLayout.setHorizontalGroup(
            jPanelModuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanelModuladaLayout.setVerticalGroup(
            jPanelModuladaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelModulada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 900, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jText_FcPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_FcPmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_FcPmActionPerformed

    private void jButtonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModActionPerformed

        
        
        
        
        
        double vc,vm,fc,fm, k,tiempo;
        vc=Double.valueOf(jText_VcPm.getText());
        vm=Double.valueOf(jText_VmPm.getText());
        fc=Double.valueOf(jText_FcPm.getText());
        fm=Double.valueOf(jText_FmPm.getText());
        k=Double.valueOf(jText_K.getText());
        tiempo=Double.valueOf(jText_Tiempo.getText());
        
        
//        graficando portadora modulada
        JPPortadorasModulacionCosPm PMPM = new JPPortadorasModulacionCosPm(vc,vm,fc,fm, k, tiempo);
        PMPM.setSize(893,100);
        jPanel_Sin_modular.removeAll();
        jPanel_Sin_modular.add(PMPM,BorderLayout.CENTER);
        jPanel_Sin_modular.revalidate();
        jPanel_Sin_modular.repaint();
        
//        señal moduladora
          JPModuladoraCosCos objModuladoraPM = new JPModuladoraCosCos(vc,vm,fc,fm, k,tiempo);
        objModuladoraPM.setSize(893,100);
        jPanel_S_Moduladora.removeAll();
        jPanel_S_Moduladora.add(objModuladoraPM,BorderLayout.CENTER);
        jPanel_S_Moduladora.revalidate();
        jPanel_S_Moduladora.repaint();


    }//GEN-LAST:event_jButtonModActionPerformed

    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonMod;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelModulada;
    private javax.swing.JPanel jPanel_S_Moduladora;
    public javax.swing.JPanel jPanel_Sin_modular;
    private javax.swing.JRadioButton jRB_FM;
    private javax.swing.JRadioButton jRB_PM;
    private javax.swing.JTextField jText_FcPm;
    private javax.swing.JTextField jText_FmPm;
    private javax.swing.JTextField jText_K;
    private javax.swing.JTextField jText_Tiempo;
    private javax.swing.JTextField jText_VcPm;
    private javax.swing.JTextField jText_VmPm;
    // End of variables declaration//GEN-END:variables
}
